language: python
python:
  - 2.7

sudo: required

services:
  - docker

before_install:
  # Shut down postgres because it blocks our db container's port map to :5432
  - sudo service postgresql stop
  # Wait for it to stop
  - while sudo lsof -Pi :5432 -sTCP:LISTEN -t; do sleep 1; done
  # Setup shell environment
  - source env.template
  # Create usb bus device directory to make api container happy
  - sudo mkdir /dev/bus/usb

install:
  - docker build -t smsntia/scos-sensor .
  - docker-compose up -d

before_script:
  - pip install -r ./src/requirements-dev.txt

script:
  - tox -c ./src/tox.ini -e coverage
  - tox -c ./src/tox.ini -e lint
  - docker ps | grep api | grep -q healthy
