language: python
python:
  - 2.7

sudo: required

services:
  - docker

before_install:
  - source env.template

install:
  - docker build -t smsntia/scos-sensor .
  - docker-compose up -d

before_script:
  - pip install -r ./src/requirements-dev.txt

script:
  - tox -c ./src/tox.ini -e coverage
  - tox -c ./src/tox.ini -e lint
  - docker ps | grep api | grep -q healthy
