version: '3'

services:
  api:
    image: smsntia/scos-sensor:${DOCKER_TAG} # DOCKER_TAG will always be 'latest' for GitHub source
    environment:
      - DEBUG
      - DOMAINS
      - GUNICORN_LOG_LEVEL
      - IPS
      - POSTGRES_PASSWORD
      - SECRET_KEY
      - DOCKER_TAG
      - GIT_BRANCH
      - IN_DOCKER=1
      - DEMO=1
    expose:
      - '8000'
    command: /entrypoints/api_entrypoint.sh

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - '80:80'
      - '443:443'
    command: >-
      /bin/sh -c
      "envsubst '$$DOMAINS'
      < /etc/nginx/nginx.conf.template
      > /etc/nginx/conf.d/default.conf
      && exec nginx -g 'daemon off;'"
    volumes:
      - ./nginx/conf.template:/etc/nginx/nginx.conf.template:ro
      - ./src/static:/var/www/scos-sensor/static:ro
      - ${SSL_CERT_PATH}:/etc/ssl/certs/ssl-cert.pem:ro
      - ${SSL_KEY_PATH}:/etc/ssl/private/ssl-cert.key:ro
    environment:
      - DOMAINS
