version: '3'

services:
  api:
    healthcheck:
      test: test ! -e /usrp_unhealthy
      interval: 10s
      timeout: 1s
      retries: 1
    restart: always
    labels:
      autoheal: "true"  # allow docker-autoheal to restart if unhealthy
    image: ntiaits/test_scossensor_api
    environment:
      - DEBUG
      - DOMAINS
      - IPS
      - SECRET_KEY
      - GUNICORN_LOG_LEVEL
    expose:
      - '8000'
    volumes:
      - ./db.sqlite3:/db.sqlite3
      - /opt/scos:/opt/scos
    devices:
      - /dev/bus/usb:/dev/bus/usb:rw
    command: /entrypoints/api_entrypoint.sh

  nginx:
    image: nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./src/static:/var/www/scos-sensor/static:ro
      - ${SSL_CERT_PATH}:/etc/ssl/certs/ssl-cert.pem:ro
      - ${SSL_KEY_PATH}:/etc/ssl/private/ssl-cert.key:ro

  # This is a stop-gap until Docker adds the capability to restart unhealthy
  # containers natively.
  #
  # https://github.com/moby/moby/issues/28400
  # https://github.com/willfarrell/docker-autoheal
  autoheal:
    image: ubuntu
    restart: on-failure
    depends_on:
      - api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./entrypoints/autoheal_entrypoint.sh:/entrypoints/autoheal_entrypoint.sh:ro
    command: /entrypoints/autoheal_entrypoint.sh

  ws_logger:
    restart: always
    image: gliderlabs/logspout
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
