version: '3'

services:
  api:
    restart: always
    build:
      args:
        - DEBUG
        - DOMAINS
        - IPS
        - SECRET_KEY
      context: ..
      dockerfile: Dockerfile
    env_file:
      - ../.env
    expose:
      - '8000'
    volumes:
      - ../:/code
    command: gunicorn -b :8000 --log-level ${GUNICORN_LOG_LEVEL} "sensor.wsgi"

  nginx:
    image: ${NGINX_IMAGE}
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ../nginx/conf.d:/etc/nginx/conf.d:ro
      - ../src/static:/var/www/scos-sensor/static:ro
      - ${SSL_CERT_PATH}:/etc/ssl/certs/ssl-cert.pem:ro
      - ${SSL_KEY_PATH}:/etc/ssl/private/ssl-cert.key:ro
