version: '3'

services:
  api:
    #restart: always
    build:
      args:
        # must explicitely pass environment as arguments for build-time use
        - DEBUG
        - DOMAINS
        - IPS
        - SECRET_KEY
      context: ..
      dockerfile: Dockerfile
    environment:
      - DEBUG
      - DOMAINS
      - IPS
      - SECRET_KEY
    volumes:
       - ../src:/src:ro
       - ../test-results:/test-results
       - ../db.sqlite3:/db.sqlite3
    tmpfs: /run
