name: 'scos-sensor test'

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  run-scos-sensor-tests:
    name: Test / Py ${{ matrix.python-version }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
        py:
          - "3.8"
          - "3.9"
          - "3.10"
    steps:
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Checkout scos-sensor
        uses: actions/checkout@v3
      - name: Install tox-gh
        run: python -m pip install tox-gh
      - name: Set up test suite
        run: tox r --notest -c ./src/tox.ini -e coverage
      - name: Run test suite
        run: tox r -c ./src/tox.ini -e coverage
        env:
          PYTEST_ADDOPTS: "-vv --durations=0"
          AUTHENTICATION: TOKEN
          CALLBACK_AUTHENTICATION: TOKEN
          SWITCH_CONFIGS_DIR: ../configs/switches

  run-scos-sensor-docker:
    name: Run SCOS Sensor / Py ${{ matrix.py }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
        py:
          - "3.8"
          - "3.9"
          - "3.10"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create Certs
        working-directory: ./scripts
        run: sh create_localhost_cert.sh

      - name: Create Fake USB # Create fake usb device node to make api container happy
        run : |
          sudo mkdir -p /dev/bus/usb/001
          sudo mknod /dev/bus/usb/001/001 c 189 260

      - name: Run Docker
        run: source ./env.template && export MOCK_SIGAN=1 && export MOCK_SIGAN_RANDOM=1 && docker-compose up -d --build

      - name: Pause # wait for containers to finish starting
        run: sleep 15

      - name: Check Logs
        run: docker-compose logs

      - name: Check Container
        run: docker ps | grep api | grep -q healthy

      - name: Stop containers
        if: always()
        run: docker-compose down
