name: 'scos-sensor test'

on: 
  workflow_dispatch:
  push:
  pull_request:

jobs:
  test-scos-sensor:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r src/requirements-dev.txt
      - run: black --check ./src
      - run: tox -c ./src/tox.ini -e coverage